### PR TITLE
[DATALAD RUNCMD] Move all files from lower cased sub dir into upper case

### PR DESCRIPTION
**Pull request by yarikoptic**
might be wrong thing to do and files must not be replaced since shows some changes to annexed and json files from what was in original capitalized named subject. Someone needs to check it all out

=== Do not change lines below ===
{
 "chain": [],
 "cmd": "bash -c 'mkdir -p ../sub-NDARVN280JTN/ses-HBNsiteCBIC/dwi; find . -type l -o -type f | while read f; do mv \"$f\" \"../sub-NDARVN280JTN/${{f//sub-ndarvn280jtn/sub-NDARVN280JTN}}\"; done'",
 "dsid": "b32508c1-d2c1-4b40-a3e3-48df49e7fa56",
 "exit": 0,
 "extra_inputs": [],
 "inputs": [],
 "outputs": [],
 "pwd": "sub-ndarvn280jtn"
}
^^^ Do not change lines above ^^^

### CODE REVIEW

**Comment by mattcieslak** [comment]
@scovitz do we have a subject with a lower case directory? If so, how did this pass the validator?

**Comment by yarikoptic** [comment]
> @scovitz do we have a subject with a lower case directory? If so, how did this pass the validator?

I think neither BIDS nor bids-validator cares ATM. Filed https://github.com/bids-standard/bids-specification/issues/857

**Comment by scovitz** [comment]
@yarikoptic great catch thanks so much for catching this! @mattcieslak it looks like both the uppercase and lowercase versions of that directory exist, so we're going to need to deal with that.

**Comment by scovitz** [comment]
@yarikoptic Thanks so much again for alerting us to this issue! There should only be one subject directory (uppercase) for sub-NDARVN280JTN now. The upper and lowercase versions of the same string did map to the same subject; however, the originally uppercase directory was missing data, so @mattcieslak and I ended up removing it and renaming the originally lowercase subject to uppercase. We were able to push the changes to GitHub, as seen in the latest commit on this repo. 

Thanks again!

**Comment by yarikoptic** [comment]
Note, as https://github.com/PennLINC/HBN_BIDS/pull/1/files shows, T1w image was somehow different in content between lower and upper case. Any idea why?

**Comment by mattcieslak** [comment]
I took a look into this and the answer is funny. The image data is identical between the uppercase and lowercase files. The difference comes from the command history added by afni to the nifti header. One has commands with the lowercase filename as input and the other has uppercase. Afni's refacer was run on each image.

**Comment by yarikoptic** [comment]
ah, I thought this dataset is just pointing to "original" HBN dataset files in fcp-indi, but apparently it has its own "life". gotcha

**Pull request closed without merging**
